"""empty message

Revision ID: 1362486c8e57
Revises: 28db350e8b61
Create Date: 2021-03-21 03:05:06.778673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1362486c8e57'
down_revision = '28db350e8b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ToDoList', sa.Column('members', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ToDoList', 'members')
    # ### end Alembic commands ###
