"""empty message

Revision ID: 26dd5f124e9e
Revises: 3a556ae0ff98
Create Date: 2021-03-20 03:35:55.025703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dd5f124e9e'
down_revision = '3a556ae0ff98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
