"""empty message

Revision ID: 8375f4702d70
Revises: 1362486c8e57
Create Date: 2021-03-21 03:36:48.459460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8375f4702d70'
down_revision = '1362486c8e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('todolist_id', sa.Integer(), nullable=True))
    op.add_column('Tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Tasks', 'CustomUser', ['user_id'], ['id'])
    op.create_foreign_key(None, 'Tasks', 'ToDoList', ['todolist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tasks', type_='foreignkey')
    op.drop_constraint(None, 'Tasks', type_='foreignkey')
    op.drop_column('Tasks', 'user_id')
    op.drop_column('Tasks', 'todolist_id')
    # ### end Alembic commands ###
